### PR TITLE
Add support for OrganizationToken type authentication

### PR DESCRIPTION
**Pull request by pastorhudson**
The api.churchcenter.com endpoint uses

` 'Authorization': f'OrganizationToken {token}'` as the authentication scheme. This pull request adds org_token as an optional argument to setting up PCO object.

It also adds PCOAuthType.ORGTOKEN

I've tested it and it works with api.churchcenter.com OrganizationTokens.

### CODE REVIEW

**Comment by pastorhudson** [comment]
@billdeitrick Can you give this a glance and see if I missed anything?

**Comment by pastorhudson** [comment]
I added a helper to get a church center org token from a church center vanity url.

**Comment by billdeitrick** [comment]
@pastorhudson Great work! I'd like to get unit tests on this before we merge it in. I'm happy to look at this when possible (would likely be the next couple of weeks), but if you'd be willing to add that would be fine too!

**Comment by pastorhudson** [comment]
How should I do unit tests? Do I just pick a church center url to test against? Check for token, and then make a request to make sure it works?

**Comment by pastorhudson** [comment]
Ah I see test_auth_config.py I should be able to add the org_token just like the other auth's easy enough.

**Comment by billdeitrick** [comment]
We might as well update the docs too: https://github.com/billdeitrick/pypco/blob/master/docs/source/gettingstarted.md#authentication

I should have some time in the next day or two to look over this more carefully and will get it merged in. I'll update the docs while I'm at it (which will make sure I know how this works. 🙂).

I'm thinking we can release this as well as a fix for #45 as v1.2.0.

**Comment by pastorhudson** [comment]
Ok I'm working on the mock response code to test getting a org_token

**Comment by pastorhudson** [comment]
Just bumping this. I think we're ready to merge

**Comment by billdeitrick** [comment]
@pastorhudson Sorry for the delay! I should have time to get this merged in tonight. I haven't had a chance to write up some documentation so I'll open an issue for getting this documented and kick that can down the road... 😛

**Pull request merged**
