### PR TITLE
Handle API requests that return 204

### PR DESCRIPTION
**Pull request by warmach**
Code to fix Issue 44 in billdeitrick/pypco

https://github.com/billdeitrick/pypco/issues/44

### CODE REVIEW

**Comment by pastorhudson** [comment]
Thanks for the PR!

Do you think we're better returning `None` for this or empty json `{}` ?

**Comment by pastorhudson** [comment]
Or perhaps a custom PCORequestException?

**Comment by billdeitrick** [comment]
@warmach Thanks for fixing this, and apologies it's taken so long to make some progress on getting it merged in! We just need to get test coverage on the change and then we'll be good to go.

@pastorhudson I think he made the right decision here with returning a null; that's a clear indication that PCO didn't send us a payload, and we don't want to throw an exception because there are legitimate calls where it looks like they return an empty payload as per #44.

**Comment by billdeitrick** [comment]
Fixed in 8bb4bff64d8494d36fd3e263bfb20088f46c0acc.

**Pull request closed without merging**
